# Configuración optimizada de Yarn
nodeLinker: node-modules
enableTelemetry: false
compressionLevel: 0

# Cache y network optimizations
enableProgressBars: false
enableTimers: false
preferInteractive: false

# Performance settings
httpTimeout: 30000
networkTimeout: 30000