import z from 'zod';

const unidadMedidaOptions = [
  "ACCION",
  "ACERVO",
  "ALUMNO",
  "ANALISIS",
  "ANIMAL",
  "ATENCION",
  "AULA",
  "AUTORIZACION",
  "BECAS",
  "BENEFICIARIO",
  "CABEZA",
  "CAMA",
  "CAMPAÑA",
  "CASO NOTIFICADO",
  "CONFIRMACION",
  "CASO TRATADO",
  "CATASTRO",
  "CERTIFICADO",
  "COMUNIDAD",
  "CONCESION",
  "CONSULTA",
  "CONTROL REALIZADO",
  "CONVENIO",
  "CREDITO OTORGADO",
  "CUADRANGULO ELABORADO",
  "CUOTA",
  "CURRICULA",
  "CURSO",
  "DIAGNOSTICO",
  "DIA - CAMA",
  "DICTAMEN",
  "DIVULGACION REALIZADA",
  "DOCUCUMENTO IDENTIFICACION EXPEDIDO",
  "DOCENTE CAPACITADO",
  "DOCUMENTO",
  "DOCUMENTO EMITIDO",
  "DOSIS", "EDAD",
  "EDIFICACION CONSTRUIDA",
  "EDICION REALIZADA",
  "EDIFICACION",
  "EMPRESA",
  "EQUIPO",
  "ESTABLECIMIENTO",
  "ESTABLECIMIENTO DE SALUD",
  "ESTACION",
  "ESTUDIO",
  "EVALUACION",
  "EVENTO CULTURAL",
  "EVENTO DEPORTIVO",
  "EXAMEN",
  "EXPEDIENTE",
  "EXPEDIENTE PROCESADO",
  "EXPEDIENTE RESUELTO",
  "EXPEDIENTE TECNICO",
  "EXPEDIENTE TRAMITADO",
  "FAMILIA",
  "FOLLETO",
  "GESTANTE CONTROLADA",
  "HECTAREA",
  "INFORME",
  "INMUEBLE",
  "INSEMINACION",
  "INSPECCION",
  "INSTALACION",
  "INTERVENCION",
  "INVESTIGACION",
  "KILOMETRO",
  "LICENCIA",
  "M2",
  "M3",
  "MANUAL",
  "MAPA",
  "METRO",
  "METRO LUZ",
  "MILES DE NUEVOS SOLES",
  "MISION",
  "MODULO",
  "MUESTRA",
  "NIÑO",
  "NORMA",
  "OBRA",
  "OPERACION",
  "PACIENTE ATENDIDO",
  "PARTO",
  "PERITAJE",
  "PERSONA",
  "PERSONA ATENDIDA",
  "PERSONA CAPACITADA",
  "PERSONA COLOCADA",
  "PERSONA EVALUADA",
  "PLAN",
  "PLANO",
  "PLANTONES",
  "PLANTULAS",
  "POSTA",
  "PROYECTO",
  "PUBLICACION",
  "PUENTE",
  "PUESTO",
  "QUEJA RESUELTA",
  "RACION",
  "RED INSTALADA",
  "REGISTRO",
  "RENTABILIDAD",
  "RESOLUCION",
  "SEMINARIO",
  "SERVICIO",
  "SISTEMA",
  "SUPERVISION",
  "TITULO",
  "TONELADA",
  "UNIDAD",
  "UNIDAD CATASTRADA",
  "VACUNA",
  "VISITA",
  "ZONA PROTEGIDA",
  "EVENTOS",
  "BONO REDIMIDO",
  "REASEGURO",
  "ENTIDAD",
  "CURIE",
  "UNIFORME ESCOLAR",
  "BUZO ESCOLAR",
  "MOCHILA ESCOLAR",
  "PAQUETE ESCOLAR",
  "PLANTAS",
  "KILOGRAMO",
  "DIQUE",
  "GRUPO",
  "BANCO GERMOPLASMA",
  "TECNOLOGIA",
  "SESION",
  "RECETA",
  "PROGRAMAS RADIALES",
  "PROGRAMAS TELEVISIVOS",
  "PLANILLA",
  "ACTO REGISTRAL",
  "ORGANIZACION SOCIAL DE BASE",
  "HORAS LECTIVAS",
  "INSCRIPCION",
  "LOTE ADJUDICADO",
  "MAQUINARIA PESADA",
  "CONTRIBUYENTE",
  "POLIZA",
  "PLANTILLA",
  "PRONOSTICO",
  "ADULTO MAYOR",
  "ADULTO",
  "ADOLESCENTE",
  "AUTORIDADES ELEGIDAS",
  "USUARIO",
  "DEPOSITOS / COLOCACIONES",
  "METRO LINEAL",
  "PORCENTAJE",
  "MEDIDOR DE AGUA POTABLE",
  "LOCALIDAD",
  "AJUSTES TARIFARIOS",
  "EPS",
  "INSTRUMENTOS REGULATORIOS",
  "PLANES TARIFARIOS CON CONFORMIDAD",
  "NUEVOS SOLES",
  "DOLARES",
  "LT./ SEG.",
  "REDES Y POSTES",
  "VEHICULOS",
  "CONTRATOS",
  "MILES DE TM",
  "ACUERDOS DEL DIRECTORIO",
  "RECLAMOS RESUELTOS E INFORMACION",
  "GESTIONES LEGALES",
  "CALIBRACIONES",
  "GLOBAL",
  "CASOS RESUELTOS",
  "NORMA APROBADA",
  "APELACIONES RESUELTAS",
  "PASAJEROS / DIA",
  "TRANSFERENCIA",
  "MEDIDAS CAUTELARES",
  "FORMULARIOS ELECTRONICOS",
  "TRANSFERENCIAS FINANCIERAS",
  "HORAS",
  "LOCAL",
  "ACCIONES DE AUDITORIA",
  "PROGRAMA EDUCATIVO",
  "CRIADERO",
  "KW",
  "ASPERSORES",
  "AUTORIDADES",
  "TELEFONOS  EN ZONAS RURALES",
  "NUMERO",
  "PERSONA PROTEGIDA",
  "CATALOGO",
  "QUINTAL",
  "ORGANIZACION",
  "PARCELA",
  "INNOVACION",
  "UNIDAD CATASTRAL",
  "PARTIDA REGISTRAL",
  "ALUMNO EVALUADO",
  "DOCENTE EVALUADO",
  "INFORME TECNICO",
  "NORMA ELABORADA",
  "NORMA PROMULGADA",
  "IIEE",
  "MUJER ALFABETIZADA",
  "PAREJA PROTEGIDA",
  "GESTANTE ATENDIDA",
  "PARTO NORMAL",
  "PARTO COMPLICADO",
  "CESAREA",
  "ATENCION PUERPERAL",
  "EGRESO",
  "ESTUDIO DE PREINVERSION",
  "GESTANTE Y / O NEONATO REFERIDO",
  "MUNICIPIO",
  "INSTANCIA INTERMEDIA",
  "HOGAR",
  "NIÑO PROTEGIDO",
  "NIÑO CONTROLADO",
  "NIÑO SUPLEMENTADO",
  "MUJER",
  "REPORTE TECNICO",
  "CENTRO POBLADO",
  "GESTANTE SUPLEMENTADA",
  "MATRIZ DE ESTANDARES",
  "MICROEMPRESA",
  "CAPACITACION",
  "MODULO REGISTRAL",
  "ACTA DE NACIMIENTO",
  "OFICINA",
  "ACTA REGISTRAL",
  "DNI EMITIDO",
  "BASE DE DATOS",
  "SISTEMA APROBADO",
  "PROGRAMA DISEÑADO",
  "INSTITUCION EDUCATIVA",
  "DIRECTOR",
  "NIÑO TRATADO",
  "RECIEN NACIDO ATENDIDO",
  "DOCENTE",
  "PROTOTIPO",
  "MODULO DE AULA",
  "MODULO DE ALUMNO",
  "MODULO DE IIEE",
  "PARTICIPANTE",
  "INSTITUCION EDUCATIVA REGISTRADA",
  "INSTITUCION EDUCATIVA CON MANTENIMIENTO",
  "REPORTE",
  "CHARLA",
  "PARTICIPACION",
  "DOCUMENTOS CARTOGRAFICOS",
  "EMPRESAS Y ESTABLECIMIENTOS",
  "CEDULAS DILIGENCIADAS",
  "INFORMANTES",
  "VIVIENDAS",
  "LOCAL REHABILITADO",
  "INSTITUTO VIAL PROVINCIAL",
  "OREC ATENDIDA",
  "PERSONA INFORMADA",
  "HOGAR CON CONEXION",
  "METROS COLUMNA DE AGUA",
  "RECLAMOS",
  "ENCUESTA",
  "RECIBOS",
  "CONEXIONES",
  "MESES",
  "SOLES/M3",
  "NUMERO DE TRABAJADORES",
  "PROCEDIMIENTOS",
  "DIAS HABILES",
  "PROPUESTAS",
  "INDICE",
  "DIAS",
  "SISTEMA DE SANEAMIENTO",
  "SISTEMA DE SANEAMIENTO CONSTRUIDO",
  "ORGANIZACION CAPACITADA",
  "HOGAR CAPACITADO",
  "OPERADOR INFORMADO",
  "LOCALIDAD CON SERVICIO DE TELECOMUNICACIONES INSTALADO",
  "OPERADOR SUPERVISADO",
  "VEHICULO CONTROLADO",
  "PUNTO DE EXPENDIO CONTROLADO",
  "VEHICULO SUPERVISADO",
  "SISTEMA DE TRATAMIENTO INSTALADO",
  "SISTEMA DE GESTION IMPLEMENTADO",
  "PUNTOS DE VERTIMENTO SUPERVISADOS",
  "ASISTENCIA TECNICA IMPLEMENTADO",
  "HECTAREA CONTROLADA",
  "HECTAREA FINANCIERAMENTE SOSTENIBLE",
  "HECTAREA CONSERVADA",
  "DOCENTE ESPECIALIZADO",
  "ESPECIALISTA ASISTIDO",
  "DIRECTOR CAPACITADO",
  "DOCENTA ASESORADO",
  "ASIENTO OFERTADO",
  "CONEXION DE INTERNET OPERATIVA",
  "SERVICIOS SUPERVISADOS",
  "TELEFONO FIJO OPERATIVO",
  "TELEFONO PUBLICO OPERATIVO",
  "USUARIOS CAPACITADOS",
];

export const nuevoIndicadorSchema = z.object( {
  codigo: z.string().min( 2, "Debe tener al menos 2 caracteres" ).max( 20, "Debe tener como máximo 20 caracteres" ),
  nombre: z.string().min( 2, "Campo requerido" ).max( 100, "Debe tener como máximo 100 caracteres" ),
  nivelIndicador: z.enum( [ "OEI", "AEI", "PE", "AO", "IG" ], "Selecciona una opción" ),
  tipoIndicador: z.enum( [ "IR", "IP", "IA" ], "Selecciona una opción" ),
  codigoSufijo: z.coerce.number().min( 1, "Debe ser un número positivo" ).optional(),
  parentId: z.string().optional().nullable(),
  mapaId: z.number().optional().nullable().or( z.literal( "" ) ),
} );


// Zod schema para validación de Indicador
export const modificarIndicadorSchema = z.object( {
  codigo: z.string().min( 1, "El código es obligatorio" ),
  nombre: z.string().min( 1, "El nombre es obligatorio" ),
  descripcion: z.string().min( 1, "La descripción es obligatoria" ).max( 500, "La descripción debe tener como máximo 500 caracteres" ),
  nivelIndicador: z.enum( [ "OEI", "AEI", "PE", "AO", "IG" ], "Selecciona una opción" ),
  tipoIndicador: z.enum( [ "IR", "IP", "IA" ], "Selecciona una opción" ),
  estado: z.boolean(),
  justificacion: z.string().min( 5, "Justificación: debe tener al menos 5 caracteres" ).max( 200, "Justificación: debe tener como máximo 200 caracteres" ).optional(),
  formula: z.string().optional(),
  sentidoEsperado: z.enum( [ "Ascendente", "Descendente" ], "Sentido esperado: debe ser Ascendente o Descendente" ).optional(),
  unidadMedida: z
    .string( "La unidad de medida es obligatoria" )
    .transform( val => val.toUpperCase() )
    .pipe( z.enum( unidadMedidaOptions, "Unidad de medida: ver tabla de unidades de medida del CEPLAN" ) ),
  frecuencia: z.string().optional(),
  fuenteDatos: z.string().optional(),
  logrosEsperados: z.string().optional(),
  lineaBase: z.string().optional(),
  parentId: z.string().optional().nullable(),
} );


// Zod schema para validación de Resultado
export const resultadoIndicadorSchema = z.object( {
  denominacion: z.string().optional(),
  descripcion: z.string().optional(),
  valor: z.coerce.number().min( 0, "Debe ser un número positivo" ),
  fechaRegistro: z.string().min( 1, "La fecha es obligatoria" ),
} );

